<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Tariff;

class TariffSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Tariff::insert([
        [
            "id" => 1,
            "type_charge" => "TP. GS. Salvadoreños",
            "amount" => "1.75",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [
            "id" => 2,
            "type_charge" => "TP. GS. Centroamericanos y extranjeros residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [
            "id" => 3,
            "type_charge" => "TP. GS. Extranjeros no residentes",
            "amount" => "10.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [
            "id" => 4,
            "type_charge" => "TP. GS. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 5,
            "type_charge" => "TP. GS. Entrada general de promoción cultural de accesabilidad de la población",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 6,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 7,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 8,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 9,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 10,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 11,
            "type_charge" => "TP. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 12,
            "type_charge" => "TP. ENSAYOS TÉCNICOS por hora o fracción, Nacionales, ensayos: De lunes a viernes.",
            "amount" => "75.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 13,
            "type_charge" => "TP. ENSAYOS TÉCNICOS por hora o fracción, Internacionales, ensayos: De lunes a viernes.",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 14,
            "type_charge" => "TP. MONTAJES por hora o fracción, Nacionales, Montaje escenográfico",
            "amount" => "75.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 15,
            "type_charge" => "TP. MONTAJES por hora o fracción, Internacionales, Montaje escenográfico",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 16,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, instituciones educativas privadas.",
            "amount" => "250.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 17,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "500.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 18,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "1500.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 19,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, con fines comerciales culturales y educativos.",
            "amount" => "1500.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 20,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, con fines comerciales culturales y educativos.",
            "amount" => "2500.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 21,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "250.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 22,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "350.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 23,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, con fines humanitarios.",
            "amount" => "250.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 24,
            "type_charge" => "TP. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, con fines humanitarios.",
            "amount" => "300.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 25,
            "type_charge" => "TP. USO DE LOBBY, nacionales, espacio que se usará para fines culturales y educativos, relacionados con exposiciones de artes visuales.",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 26,
            "type_charge" => "TP. USO DE LOBBY, internacionales, espacio que se usará para fines culturales y educativos, relacionados con exposiciones de artes visuales.",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 27,
            "type_charge" => "TP. USO DE LOBBY, nacionales, espacio que se usará para fines culturales y educativos, relacionados con: charlas, conferencias, foros, conversatorios, talleres, etc.",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 28,
            "type_charge" => "TP. USO DE LOBBY, internacionales, espacio que se usará para fines culturales y educativos, relacionados con: charlas, conferencias, foros, conversatorios, talleres, etc.",
            "amount" => "100.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 29,
            "type_charge" => "TP. USO DE LOBBY (3 áreas), nacionales, venta de productos varios, por área (derecha, izquierda o central) y por sesión de 4 horas o fracción).",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 30,
            "type_charge" => "TP. USO DE LOBBY (3 áreas), internacionales, venta de productos varios, por área (derecha, izquierda o central) y por sesión de 4 horas o fracción).",
            "amount" => "150.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 31,
            "type_charge" => "TP. USO DE LOBBY (3 áreas), nacionales, para exposiciones con fines artísticos o culturales (por 1 semana o fracción).",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 32,
            "type_charge" => "TP. USO DE LOBBY (3 áreas), internacionales, para exposiciones con fines artísticos o culturales (por 1 semana o fracción).",
            "amount" => "150.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 33,
            "type_charge" => "TP. USO DE PIANO DE CONCIERTO DENTRO DE LAS INSTALACIONES DEL TEATRO, nacionales, Piano YAMAHA C7F11 Serie 5210246 para ensayo de 4 horas o fracción.",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 34,
            "type_charge" => "TP. USO DE PIANO DE CONCIERTO DENTRO DE LAS INSTALACIONES DEL TEATRO, internacionales, Piano YAMAHA C7F11 Serie 5210246 para ensayo de 4 horas o fracción.",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 35,
            "type_charge" => "TP. USO DE PIANO DE CONCIERTO DENTRO DE LAS INSTALACIONES DEL TEATRO, nacionales, Piano YAMAHA C7F11 Serie 5210246 por función o por concierto.",
            "amount" => "350.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 36,
            "type_charge" => "TP. USO DE PIANO DE CONCIERTO DENTRO DE LAS INSTALACIONES DEL TEATRO, internacionales, Piano YAMAHA C7F11 Serie 5210246 por función o por concierto.",
            "amount" => "500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 37,
            "type_charge" => "TP. ESTACIONAMIENTO DE VEHÍCULOS LIVIANOS, Por hora o fracción.",
            "amount" => "1.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 38,
            "type_charge" => "TP. ESTACIONAMIENTO DE VEHÍCULOS LIVIANOS, Semanal.",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 39,
            "type_charge" => "TP. ESTACIONAMIENTO DE VEHÍCULOS LIVIANOS, Quincenal.",
            "amount" => "20.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 40,
            "type_charge" => "TP. ESTACIONAMIENTO DE VEHÍCULOS LIVIANOS, Mensual.",
            "amount" => "35.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 41,
            "type_charge" => "TP. ESTACIONAMIENTO DE MOTOCICLETAS, Por hora o fracción.",
            "amount" => "1.00",
            "rent" => "Hora",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 42,
            "type_charge" => "TP. ESTACIONAMIENTO DE MOTOCICLETAS, Semanal.",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 43,
            "type_charge" => "TP. ESTACIONAMIENTO DE MOTOCICLETAS, Quincenal.",
            "amount" => "12.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [ 
            "id" => 44,
            "type_charge" => "TP. ESTACIONAMIENTO DE MOTOCICLETAS, Mensual.",
            "amount" => "20.00",
            "rent" => "Día/Evento",
            "dependence_id" => 8,
        ],
        [
            "id" => 45,
            "type_charge" => "TN. GS. Salvadoreños",
            "amount" => "1.75",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 46,
            "type_charge" => "TN. GS. Centroamericanos y extranjeros residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 47,
            "type_charge" => "TN. GS. Extranjeros no residentes",
            "amount" => "10.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 48,
            "type_charge" => "TN. GS. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 49,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 50,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 51,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 52,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 53,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 54,
            "type_charge" => "TN. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 55,
            "type_charge" => "TN. GS. ENSAYOS TÉCNICOS por hora o fracción, Nacionales, ensayos: De lunes a viernes.",
            "amount" => "75.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 56,
            "type_charge" => "TN. GS. ENSAYOS TÉCNICOS por hora o fracción, Internacionales, ensayos: De lunes a viernes.",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 57,
            "type_charge" => "TN. GS. MONTAJES por hora o fracción, Nacionales, Montaje escenográfico",
            "amount" => "75.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 58,
            "type_charge" => "TN. GS. MONTAJES por hora o fracción, Internacionales, Montaje escenográfico",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 59,
            "type_charge" => "TN. PS. ENSAYOS TÉCNICOS por hora o fracción, Nacionales, ensayos: De lunes a viernes.",
            "amount" => "30.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 60,
            "type_charge" => "TN. PS. ENSAYOS TÉCNICOS por hora o fracción, Internacionales, ensayos: De lunes a viernes.",
            "amount" => "60.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 61,
            "type_charge" => "TN. PS. MONTAJES por hora o fracción, Nacionales, Montaje escenográfico",
            "amount" => "30.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 62,
            "type_charge" => "TN. PS. MONTAJES por hora o fracción, Internacionales, Montaje escenográfico",
            "amount" => "60.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [
            "id" => 63,
            "type_charge" => "TN. PS. Salvadoreños",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 64,
            "type_charge" => "TN. PS. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 65,
            "type_charge" => "TN. PS. Extranjeros no residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 66,
            "type_charge" => "TN. PS. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 67,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones educativas privadas.",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 68,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 69,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "300.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 70,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, con fines comerciales culturales y educativos.",
            "amount" => "1500.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 71,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, con fines comerciales culturales y educativos.",
            "amount" => "2500.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 72,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 73,
            "type_charge" => "TN. GS. USO DE GRAN SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 74,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones educativas privadas.",
            "amount" => "25.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 75,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, a instituciones educativas privadas.",
            "amount" => "60.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 76,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "50.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 77,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "75.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 78,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones con fines comerciales culturales y educativos.",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 79,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, a instituciones con fines comerciales culturales y educativos.",
            "amount" => "300.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 80,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), nacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "30.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 81,
            "type_charge" => "TN. PS. USO DE PEQUEÑA SALA PARA EVENTOS (por 6 horas, incluye montaje), internacionales, a instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "30.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 82,
            "type_charge" => "TN. USO DE ESPACIOS PARA CAFÉ TEATRO, nacionales, espacio por mes.",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 83,
            "type_charge" => "TN. USO DE ESPACIOS PARA CAFÉ TEATRO, nacionales, costo por sesión de 4 horas o fracción.",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 84,
            "type_charge" => "TN. USO DE ESPACIOS PARA CAFÉ TEATRO, internacionales, costo por sesión de 4 horas o fracción.",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 85,
            "type_charge" => "TN. USO DE GRAN FOYER, VESTIBULO, AMBULATORIOS, SALA DE CÁMARA Y SALON TRAS CABINA, nacionales, estos espacios se usarán con propósitos educativos y culturales, para exposiciones de artes visuales, charlas, conferencias, foros, conversatorios y talleres.",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 86,
            "type_charge" => "TN. USO DE GRAN FOYER, VESTIBULO, AMBULATORIOS, SALA DE CÁMARA Y SALON TRAS CABINA, internacionales, estos espacios se usarán con propósitos educativos y culturales, para exposiciones de artes visuales, charlas, conferencias, foros, conversatorios y talleres.",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 87,
            "type_charge" => "TN. USO DE GRAN FOYER, VESTIBULO, AMBULATORIOS, SALA DE CÁMARA Y SALON TRAS CABINA, nacionales, Sala de Cámara se usará para fines artísticos (por día).",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [ 
            "id" => 88,
            "type_charge" => "TN. USO DE GRAN FOYER, VESTIBULO, AMBULATORIOS, SALA DE CÁMARA Y SALON TRAS CABINA, internacionales, Sala de Cámara se usará para fines artísticos (por día).",
            "amount" => "100.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 89,
            "type_charge" => "TSA. GS. Salvadoreños",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 90,
            "type_charge" => "TSA. GS. Centroamericanos y extranjeros residentes",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 91,
            "type_charge" => "TSA. GS. Extranjeros no residentes",
            "amount" => "3.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 92,
            "type_charge" => "TSA. GS. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 93,
            "type_charge" => "TSA. GS. Entrada general de promoción cultural de accesibilidad de la población al Teatro",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 94,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, nacionales, filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "50.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 95,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, internacionales, filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario diurno de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 96,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, nacionales, filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 97,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, internacionales, filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario nocturno de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "150.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 98,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, nacionales, filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 99,
            "type_charge" => "TSA. GS. FILMACIONES Y FOTOGRAFIAS, internacionales, filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 100,
            "type_charge" => "TSA. FOYER, Espacio por evento máximo 4 horas.",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 101,
            "type_charge" => "TSA. VESTÍBULO, SALÓN DE PAVORREALES Y SALÓN DE FUMADORES, Espacio por evento máximo 4 horas.",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 102,
            "type_charge" => "TSA. SALÓN CANTINA, Espacio por evento máximo 4 horas.",
            "amount" => "200.00",
            "rent" => "Hora",
            "dependence_id" => 9,
        ],
        [
            "id" => 103,
            "type_charge" => "TSA. SALÓN CANTINA, Espacio por mes.",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 104,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), nacionales, a Público estudiantil y público en general.",
            "amount" => "130.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 105,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), internacionales, a Público estudiantil y público en general.",
            "amount" => "250.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 106,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), nacionales, a instituciones con fines comerciales.",
            "amount" => "500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 107,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), internacionales, a instituciones con fines comerciales.",
            "amount" => "1000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 108,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), nacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 109,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), internacionales, academias de artes privadas y compañías profesionales independientes.",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 110,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), nacionales, a instituciones o corporaciones del Estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 111,
            "type_charge" => "TSA. GS. USO DE GRAN SALA PARA EVENTOS (por día), internacionales, a instituciones o corporaciones del Estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "100.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 112,
            "type_charge" => "TNFG. SM. Salvadoreños",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 113,
            "type_charge" => "TNFG. SM. Centroamericanos y extranjeros residentes",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 114,
            "type_charge" => "TNFG. SM. Extranjeros no residentes",
            "amount" => "3.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 115,
            "type_charge" => "TNFG. SM. Estudiantes con carné vigente, personas con discapacidad adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 116,
            "type_charge" => "TNFG. SM. Entrada general de promoción cultural de accesibilidad de la población al Teatro",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 117,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "30.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 118,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario de 8:00 a.m. a 7:00 p.m.)",
            "amount" => "100.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 119,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "60.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 120,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y toma de fotografía con fines comerciales por hora o fracción. (horario de 7:00 p.m. a 9:00 p.m.)",
            "amount" => "125.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 121,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, nacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 122,
            "type_charge" => "TNFG. SM. FILMACIONES Y FOTOGRAFIAS, internacionales, Filmaciones y fotografías con fines culturales y educativos (en horario regular de atención del teatro, sin exclusividad ni equipo profesional)",
            "amount" => "0.00",
            "rent" => "Hora",
            "dependence_id" => 10,
        ],
        [
            "id" => 123,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, nacionales, A Público estudiantil y público en general.",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 124,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, internacionales, A Público estudiantil y público en general.",
            "amount" => "100.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 125,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, nacionales, Con fines comerciales.",
            "amount" => "300.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 126,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, internacionales, Con fines comerciales.",
            "amount" => "800.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 127,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, nacionales, Academias de artes privadas y compañías profesionales independientes.",
            "amount" => "500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 128,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, internacionales, Academias de artes privadas y compañías profesionales independientes.",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 129,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, nacionales, A Instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "50.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 130,
            "type_charge" => "TNFG. SM. USO DE GRAN SALA PARA EVENTOS, nacionales, A Instituciones o corporaciones del estado, representaciones diplomáticas, consulares y organismos internacionales acreditados en el país.",
            "amount" => "75.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 131,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Salvadoreños",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 10,
        ],
        [
            "id" => 132,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Centroamericanos y extranjeros residentes",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 133,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Extranjeros no residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 134,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Estudiantes con carné vigente, personas con discapacidad adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 135,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Salvadoreños",
            "amount" => "3.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 136,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Centroamericanos y extranjeros residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 137,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Extranjeros no residentes",
            "amount" => "7.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 138,
            "type_charge" => "TN. SS. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 7,
        ],
        [
            "id" => 139,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Salvadoreños",
            "amount" => "1.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 140,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Centroamericanos y extranjeros residentes",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 141,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Extranjeros no residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 142,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (con acceso restringido para toma de fotografías) Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 143,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Salvadoreños",
            "amount" => "3.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 144,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Centroamericanos y extranjeros residentes",
            "amount" => "5.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 145,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Extranjeros no residentes",
            "amount" => "7.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 146,
            "type_charge" => "TN. SA. RECORRIDOS Y VISITAS GUIADAS (sin acceso restringido para toma de fotografías sin flash) Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "2.00",
            "rent" => "Día/Evento",
            "dependence_id" => 9,
        ],
        [
            "id" => 147,
            "type_charge" => "ORQUESTA SINFÓNICA DE EL SALVADOR, Área de San Salvador, Elenco completo",
            "amount" => "2000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 4,
        ],
        [
            "id" => 148,
            "type_charge" => "ORQUESTA SINFÓNICA DE EL SALVADOR, Área de San Salvador, Elenco menor o igual a 25 músicos",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 4,
        ],
        [
            "id" => 149,
            "type_charge" => "ORQUESTA SINFÓNICA DE EL SALVADOR, Fuera del Área de San Salvador, Elenco completo",
            "amount" => "3000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 4,
        ],
        [
            "id" => 150,
            "type_charge" => "ORQUESTA SINFÓNICA DE EL SALVADOR, Fuera del Área de San Salvador, Elenco menor o igual a 25 músicos",
            "amount" => "2000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 4,
        ],
        [
            "id" => 151,
            "type_charge" => "CORO NACIONAL DE EL SALVADOR, Área de San Salvador",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 5,
        ],
        [
            "id" => 152,
            "type_charge" => "CORO NACIONAL DE EL SALVADOR, Fuera del Área de San Salvador",
            "amount" => "2000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 5,
        ],
        [
            "id" => 153,
            "type_charge" => "BALLET FOLKLÓRICO NACIONAL DE EL SALVADOR, Área de San Salvador",
            "amount" => "1200.00",
            "rent" => "Día/Evento",
            "dependence_id" => 2,
        ],
        [
            "id" => 154,
            "type_charge" => "BALLET FOLKLÓRICO NACIONAL DE EL SALVADOR, Fuera del Área de San Salvador",
            "amount" => "1800.00",
            "rent" => "Día/Evento",
            "dependence_id" => 2,
        ],
        [
            "id" => 155,
            "type_charge" => "BALLET FOLKLÓRICO NACIONAL DE EL SALVADOR, Área de San Salvador, Presentaciones de pequeño formato (Espectáculo con elenco de 4 parejas de bailarines sin músicos) o presentación solamente de músicos",
            "amount" => "700.00",
            "rent" => "Día/Evento",
            "dependence_id" => 2,
        ],
        [
            "id" => 156,
            "type_charge" => "BALLET FOLKLÓRICO NACIONAL DE EL SALVADOR, Fuera del Área de San Salvador, Presentaciones de pequeño formato (Espectáculo con elenco de 4 parejas de bailarines sin músicos) o presentación solamente de músicos",
            "amount" => "1000.00",
            "rent" => "Día/Evento",
            "dependence_id" => 2,
        ],
        [
            "id" => 157,
            "type_charge" => "COMPAÑÍA NACIONAL DE DANZA, Área de San Salvador",
            "amount" => "1200.00",
            "rent" => "Día/Evento",
            "dependence_id" => 1,
        ],
        [
            "id" => 158,
            "type_charge" => "COMPAÑÍA NACIONAL DE DANZA, Fuera del área de San Salvador",
            "amount" => "1500.00",
            "rent" => "Día/Evento",
            "dependence_id" => 1,
        ],
        [
            "id" => 159,
            "type_charge" => "BALLET NACIONAL DE EL SALVADOR, Área de San Salvador",
            "amount" => "1300.00",
            "rent" => "Día/Evento",
            "dependence_id" => 3,
        ],
        [
            "id" => 160,
            "type_charge" => "BALLET NACIONAL DE EL SALVADOR, Fuera del área de San Salvador",
            "amount" => "1700.00",
            "rent" => "Día/Evento",
            "dependence_id" => 3,
        ],

        /* [
            "id" => 1,
            "service_place_id" => 8,
            "type_charge" => "PR. ID. Salvadoreños",
            "amount" => "0.75",
        ],
        [
            "id" => 41,
            "service_place_id" => 8,
            "type_charge" => "PR. ID. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 42,
            "service_place_id" => 8,
            "type_charge" => "PR. ID. Extranjeros no residentes",
            "amount" => "5.00",
        ],
        [
            "id" => 43,
            "service_place_id" => 8,
            "type_charge" => "PR. ID. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
        ],
        [
            "id" => 44,
            "service_place_id" => 9,
            "type_charge" => "PSH. MHN. SV. Salvadoreños",
            "amount" => "1.00",
        ],
        [
            "id" => 45,
            "service_place_id" => 9,
            "type_charge" => "PSH. MHN. SV. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 46,
            "service_place_id" => 9,
            "type_charge" => "PSH. MHN. SV. Extranjeros no residentes",
            "amount" => "5.00",
        ],
        [
            "id" => 47,
            "service_place_id" => 9,
            "type_charge" => "PSH. MHN. SV. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
        ],
        [
            "id" => 48,
            "service_place_id" => 10,
            "type_charge" => "P. ZN. Salvadoreños",
            "amount" => "1.00",
        ],
        [
            "id" => 49,
            "service_place_id" => 10,
            "type_charge" => "P. ZN. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 50,
            "service_place_id" => 10,
            "type_charge" => "P. ZN. Extranjeros no residentes",
            "amount" => "5.00",
        ],
        [
            "id" => 51,
            "service_place_id" => 10,
            "type_charge" => "P. ZN. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
        ],
        [
            "id" => 52,
            "service_place_id" => 11,
            "type_charge" => "PNA. DR. DJG. Salvadoreños",
            "amount" => "1.00",
        ],
        [
            "id" => 53,
            "service_place_id" => 11,
            "type_charge" => "PNA. DR. DJG. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 54,
            "service_place_id" => 11,
            "type_charge" => "PNA. DR. DJG. Extranjeros no residentes",
            "amount" => "10.00",
        ],
        [
            "id" => 55,
            "service_place_id" => 11,
            "type_charge" => "PNA. DR. DJG. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
        ],
        [
            "id" => 56,
            "service_place_id" => 11,
            "type_charge" => "PNA. DR. DJG. Uso de audioguía",
            "amount" => "3.00",
        ],
        [
            "id" => 57,
            "service_place_id" => 12,
            "type_charge" => "MR. ORI. OCI. Salvadoreños",
            "amount" => "1.00",
        ],
        [
            "id" => 58,
            "service_place_id" => 12,
            "type_charge" => "MR. ORI. OCI. Centroamericanos y extranjeros residentes",
            "amount" => "2.00",
        ],
        [
            "id" => 59,
            "service_place_id" => 12,
            "type_charge" => "MR. ORI. OCI. Extranjeros no residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 60,
            "service_place_id" => 12,
            "type_charge" => "MR. ORI. OCI. Estudiantes con carné",
            "amount" => "0.00",
        ],
        [
            "id" => 61,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Salvadoreños",
            "amount" => "1.00",
        ],
        [
            "id" => 62,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Centroamericanos y extranjeros residentes",
            "amount" => "3.00",
        ],
        [
            "id" => 63,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Extranjeros no residentes",
            "amount" => "5.00",
        ],
        [
            "id" => 64,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Extranjeros no residentes (JOYA DE CERÉN, Patrimonio de la Humanidad)",
            "amount" => "10.00",
        ],
        [
            "id" => 65,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Extranjeros residentes Joya de Cerén, Patrimonio de la Humanidad",
            "amount" => "7.00",
        ],
        [
            "id" => 66,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Estudiantes con carné vigente, personas con discapacidad, adultos mayores y niños menores de 12 años",
            "amount" => "0.00",
        ],
        [
            "id" => 67,
            "service_place_id" => 13,
            "type_charge" => "PA. SA. JC. TZM. CIHT. Residentes de los municipios en los cuales se encuentran los parques arqueológicos",
            "amount" => "0.00",
        ],  */
        ]);
    }
}
